site_name: AMRIT
site_url: https://psmri.github.io/

nav:
    - Home: index.md
    - Projects Guide: 
        - Overview : module-guides/functional-overview.md
        - Health and Wellness : module-guides/hwc.md
        - 104 Service : module-guides/104.md
        - 1097 Service : module-guides/1097.md
        - MMU Service : module-guides/mmu.md
        - MCTS Service : module-guides/mcts.md
        - FHIR Service : module-guides/fhir.md
    - Developer Guide : 
        - Overview : developer-guides/technical-overview.md
        - Core Technologies : developer-guides/core-technologies.md
        - Release Strategy : developer-guides/release-strategy.md
    - Community :
        - Overview : community/community-overview.md
        - Contributing : community/contributing.md
        - Roadmap : community/roadmap.md 
    - About : 
        - Release Notes : about/release-notes.md
        - License : about/license.md
    - API-Reference :
        - Admin : api-reference/admin-api-spec.md
        - Common : api-reference/common-api-spec.md
        - ECD : api-reference/ecd-api-spec.md
        - FHIR : api-reference/fhir-api-spec.md
        - Helpline-104 : api-reference/helpline104-api-spec.md
        - Helpline-1097 : api-reference/helpline1097-api-spec.md
        - HelplineMCTS : api-reference/helplinemcts-api-spec.md
        - HWC : api-reference/hwc-api-spec.md   
        - Identity : api-reference/identity-api-spec.md
        - Inventory : api-reference/inventory-api-spec.md
        - MMU : api-reference/mmu-api-spec.md
        - Scheduler : api-reference/scheduler-api-spec.md
        - TM : api-reference/tm-api-spec.md
extra_css:
    - css/extra.css

plugins :
    - swagger-ui-tag    